Repository AYU-CAMPUS/AYU-FE, pull requests merged in 2022-11, with the labels that each got.

#10 feature: tailwind.config 세팅
  package-lock.json
  package.json
  pages/_document.js
  pages/index.tsx
  styles/globals.css
  tailwind.config.js
Labels: enhancement

#6 Feature/forgot-password
  components/Forgot/ForgotPasswordForm.style.ts
  components/Forgot/ForgotPasswordForm.tsx
  components/Layout/MainLayout.style.ts
  pages/sign/forgot-password/ForgotPassword.style.ts
  pages/sign/forgot-password/index.tsx
Labels: feat

#2 Feature/my page
  .eslintrc.js
  components/Button/Button.tsx
  components/Layout/MainLayout.tsx
  components/Modal/Portal/Portal.tsx
  components/Modal/WithdrawlModal.style.tsx
  components/Modal/WithdrawlModal.tsx
  components/MyPage/MyPageComponent.style.ts
  components/MyPage/MyPageComponent.tsx
  components/MyPage/MyPageDataList/DataList.tsx
  components/MyPage/MyPageDataList/style.tsx
  components/MyPage/MyPageInfo/ChangePassword.tsx
  components/MyPage/MyPageInfo/DownloadData.tsx
  components/MyPage/MyPageInfo/ExchangeAcceptance.tsx
  components/MyPage/MyPageInfo/MyInformation.tsx
  components/MyPage/MyPageInfo/MyPageInfo.style.tsx
  components/MyPage/MyPageInfo/Notification.tsx
  components/MyPage/MyPageInfo/PostMyData.tsx
  components/MyPage/MyPageInfo/TableContainer.style.tsx
  components/MyPage/MyPageInfo/types.ts
  components/MyPage/MyPageNav/MyPageNav.tsx
  components/MyPage/MyPageNav/style.tsx
  components/MyPage/MyPageNav/types.ts
  components/MyPage/MyPageNavData/MyPageNavData.tsx
  components/MyPage/MyPageNavData/style.tsx
  components/MyPage/MyPageNavTitle/TitleDescription.tsx
  components/MyPage/MyPageProfile/Profile.tsx
  components/MyPage/MyPageProfile/style.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/mypage/index.tsx
  public/images/ArrowBtn.png
  public/images/EditBtn.png
  public/images/Profile.png
  public/images/ProfileImage.png
  public/images/alarm.svg
  public/images/exchangeAlarm.svg
  public/images/search.svg
  styles/Home.module.css
  styles/globals.css
  styles/reset.css
  utils/hookFormUtil.ts
Labels: feat, frontend

#9 Feature/markup main page
  .eslintrc.js
  components/Article/Category.style.ts
  components/Article/Category.tsx
  components/Article/CategorySelection.style.ts
  components/Article/CategorySelection.tsx
  components/Article/Culture.style.tsx
  components/Article/Culture.tsx
  components/Article/DataCategoryAside.tsx
  components/Article/Department.style.ts
  components/Article/Department.tsx
  components/Article/data.ts
  components/Header/Header.style.tsx
  components/Header/Header.tsx
  components/Input/Input.tsx
  components/MainPage/DataJson.ts
  components/MainPage/DataView.style.ts
  components/MainPage/DataView.tsx
  components/MainPage/MainPage.style.ts
  components/MainPage/MainPage.tsx
  components/MyPage/MyPageComponent.tsx
  components/MyPage/MyPageNavData/MyPageNavData.tsx
  components/MyPage/MyPageNavData/types.ts
  package.json
  pages/article/category.tsx
  pages/article/culture.tsx
  pages/article/department.tsx
  pages/article/index.tsx
  public/images/BannerStarbucks.png
  public/images/BannerTitle.png
  public/images/LeftArrow.png
  public/images/communication.svg
  public/images/convergencePractice.svg
  public/images/dot.svg
  public/images/global.svg
  public/images/leaderShip.svg
  public/images/problemSolving.svg
  styles/globals.css
Labels: feat, frontend

#13 Feat/markup manger page
  components/Manager/ArticleReport/ArticleReport.style.ts
  components/Manager/ArticleReport/ArticleReport.tsx
  components/Manager/ArticleReport/TableData.ts
  components/Manager/AsideNavbar/AsideNavbar.style.ts
  components/Manager/AsideNavbar/AsideNavbar.tsx
  components/Manager/CommentReport/CommentReport.style.ts
  components/Manager/CommentReport/CommentReport.tsx
  components/Manager/CommentReport/TableData.ts
  components/Manager/Dashboard/Dashboard.style.ts
  components/Manager/Dashboard/Dashboard.tsx
  components/Manager/Manager.style.ts
  components/Manager/Manager.tsx
  components/Manager/NavbarData.ts
  components/Manager/NavbarInfo/NavbarInfo.tsx
  components/Manager/NavbarTitle.tsx
  components/Manager/RequestList/RequestList.style.ts
  components/Manager/RequestList/RequestList.tsx
  components/Manager/SearchSection/SearchSection.style.ts
  components/Manager/SearchSection/SearchSection.tsx
  components/Manager/UserManagement/TableData.ts
  components/Manager/UserManagement/UserManagement.style.ts
  components/Manager/UserManagement/UserManagement.tsx
  package.json
  pages/manager/index.tsx
  public/images/articleReport.svg
  public/images/commentReport.svg
  public/images/dashBoard.svg
  public/images/date.svg
  public/images/hamburger.svg
  public/images/list.svg
  public/images/userManagement.svg
Labels: feat, frontend
